### PR TITLE
Add logging and math functions back to the project.

### PR DESCRIPTION
**Pull request by NullCascade**
Stack still needs some adjustments, but the logic for the following functions are written:

- xLogMessage
- xAnd
- xArcCos
- xArcSin
- xArcTan
- xBitAnd
- xBitNot
- xBitOr
- xBitXor
- xCos
- xDegRad
- xFloatsToLong
- xHypot
- xLongToFloats
- xNot
- xOr
- xPow
- xRadDeg
- xRandomFloat
- xRandomLong
- xShift
- xSin
- xSqrt
- xTan
- xXor

### CODE REVIEW

**Comment by NullCascade** [comment]
Updated to also include a bunch of simple math-related functions. I have a test case esp file I'm working on that has various scripts, in the test_<functionname> format that tests various inputs to the above functions.

**Comment by NullCascade** [comment]
Whoops, thought I didn't commit those build events. Removed.

Which functions in particular are you referring to with matching 0.9 functionality? The exact method isn't necessarily the way we do it with the new engine. If you try to pop with 0.10, it will return false. I added a size() function to the stack so you can tell if there's something to pop. Do you want the stack functions to take this into account somehow (exceptions are an option if we're not expecting them to happen, otherwise that can be a performance hit)? Or do you want them to better emulate the old version? Or, are you referring to the combined `push(pop())` sort of code? These were added quickly just to get stuff to write test cases for to debug 0.10. Let me know what you prefer and I'll adjust the functions.

I'll look into xLogMessage. I tweaked it to get the right values printed in my test cases, as (because of the stack difference) numbers were not being printed correctly. This specifically happens when short or long values are passed as literals. I think it's because of how MWEdit defines the variables when it can be short, long, or float and it doesn't know which type to use. Do you have any insights there? Having the function was necessary to test other functions to expose bugs in the VM (such as the one with literals).

**Comment by NullCascade** [comment]
- Removed the post-build events.
- Added `stack.empty()`, to determine if there's anything in the stack.
- Made use of that function to better guard xLogMessage.
- Changed xLogMessage to better follow 0.9's logic.

**Comment by Merzasphor** [comment]
I was mainly referring to things like xOr/xAnd, where the slight change introduces a side effect that's not immediately obvious. In this case, you caught the issue quickly. :-) I'm not saying that we need to match the 0.9 implementation forever, but that it (or something close to it) should be the initial version here. We'll need to adjust to the new interfaces, but we should otherwise try to match the logic for that version. There are definitely still some bugs in a few 0.9 functions, but many of them have been tested extensively; I'm hoping to avoid introducing any new bugs in the translation process.

Regarding xLogMessage: I just didn't want any of the 0.9 functionality to get lost in the transition.

**Pull request merged**
